<?php
$config["github"]=array(
"git"=>array(
       "sitekey"=>md5("qiaoqianwu123"),
       "site"=>"https://blog.xcyd.fun",
       "webp"=>true,
       "path"=>"",
       "username"=>"MQiaoqian",
       "repos"=>"MCDN",
       "Parameter"=>false,
       "CacheTime"=>0,
       "AnyAgency"=>false,
       "InstallAgency"=>false,
       "token"=>"81fcd707964fbe80d8af1af9e739eb20bc94f8d8"
          )
);
